apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry # this is a HTTP service, so only ServiceEntry is needed
metadata:
  name: worldclockapi-ext # allows http://worldclockapi.com/api/json/est/now endpoint
spec:
  hosts:
  - worldclockapi.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry # this is a HTTPS service, so ServiceEntry and VirtualService is needed
metadata:
  name: google # allows https://www.google.com endpoint
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100