apiVersion: v1
kind: ConfigMap
metadata:
  name: externalcfg
  namespace: eshop
  labels:
    app: eshop  
data:
  basket__ConnectionString: basket-data
  catalog__ConnectionString: Server=sql-data;Initial Catalog=eShopOnK8S.CatalogDb;User Id=sa;Password=Pass@word;
