apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ template "fullname" . }}-sql-instance
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterServiceClassExternalName: azure-sql-12-0
  clusterServicePlanExternalName: {{ .Values.externalDatabase.azure.servicePlan }}
  parameters:
    location: {{ .Values.externalDatabase.azure.location }}
    resourceGroup: {{ .Values.externalDatabase.azure.resourceGroup }}
  #  sslEnforcement: enabled
    firewallRules:
    - startIPAddress: "0.0.0.0"
      endIPAddress: "255.255.255.255"
      name: "AllowAll"