{{- if .Values.ingress.enabled -}}
{{- $fullName := include "webmvc.fullname" . -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
        {{- if .Values.ingress.paths -}}
        {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            backend:
              serviceName: "{{ .serviceName }}"
              servicePort: 80        
        {{- end -}}
        {{- end }}
{{- end }}