apiVersion: v1
kind: Service
metadata:
  name: {{ template "sql.name" . }}
  labels:
    app: {{ .Values.appName }}
    chart: "{{ .Chart.Name }}-{{.Chart.Version}}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.component }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.appName }}
    component: {{ .Values.component }}
    release: {{ .Release.Name }}
